
spring:
  application:
    name: hello-service
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname:}:1111/eureka/
server:
  port: 8001